name: Release

on:
  push:

jobs:
  push_to_registry:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hugo.Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=joshcarp/hugo:latest
          cache-to: type=inline
          tags: joshcarp/hugo:latest