name: Release

on:
  push:

jobs:
  push_to_registry:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: docker.io/joshcarp/hugo
          tag_with_ref: true
          dockerfile: ./hugo.Dockerfile
          tags: latest
          add_git_labels: true